#!/bin/bash
#
### INSTRUCTIONS - WORK IN PROGRESS
### ============
##
### Copy sitemap from learnosm to the source files of this folder.
rm ~/Github/LearnOSM-language-helper/sitemap/sitemap-1.xml
cp -u ~/Github/learnosm/_site/sitemap.xml ~/Github/LearnOSM-language-helper/sitemap/sitemap-1.xml
cd ~/Github/LearnOSM-language-helper/sitemap
#
### Edit sitemap-1.xml - remove the old header & insert a new one.
sed -i '1,2d' sitemap-1.xml
sed -i '1 r sitemap-header.xml' sitemap-1.xml
sed -i '1d' sitemap-1.xml
sed -i '/\<lastmod/d' sitemap-1.xml
sed -i 's/localhost\:4000/learnosm\.org/g' sitemap-1.xml
sed -i 's/nl_NL/nl/g' sitemap-1.xml
sed -i 's/zh_CN/zh/g' sitemap-1.xml
sed -i 's/zh_TW/tw/g' sitemap-1.xml
sed -i '/org\/cs\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/de\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/en\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/es\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/fa\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/fr\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/hr\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/hu\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/id\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/it\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/ja\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/ko\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/my\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/nb\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/nl\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/pl\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/pt\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/ru\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/sq\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/sw\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/uk\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/vi\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/zh\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/cs\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/de\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/en\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/es\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/fa\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/fr\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/hr\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/hu\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/id\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/it\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/ja\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/ko\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/my\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/nb\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/nl\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/pl\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/pt\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/ru\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/sq\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/sw\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/uk\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/vi\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/zh\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/fa\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/hr\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/hu\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/ko\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/nb\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/nl\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/ru\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/sq\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/uk\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/cn\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/tw\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/zh\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/fa\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/hr\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/hu\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/ko\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/nb\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/nl\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/ru\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/sq\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/uk\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/cn\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/tw\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/zh\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/fa\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/hr\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/hu\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/ko\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/nb\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/nl\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/ru\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/sq\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/uk\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/cn\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/tw\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/zh\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/ko\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/nl\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/cn\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/tw\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/nl\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/cn\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/tw\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/fa\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/hr\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/nb\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/nl\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/ru\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/uk\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/cn\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/tw\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/es\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/fr\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/nb\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/nl\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/pl\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/pt\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/ru\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/sw\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/uk\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/cn\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/tw\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/es\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/fr\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/hr\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/nl\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/pt\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/ru\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/sw\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/uk\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/tw\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/hr\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/nl\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/ru\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/sw\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/uk\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/tw\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
cp sitemap-1.xml ../output/sitemap.xml