#!/bin/bash
#
### INSTRUCTIONS - WORK IN PROGRESS
### ============
##
### Copy sitemap from learnosm to the source files of this folder.
rm ~/Github/LearnOSM-language-helper/sitemap/sitemap-1.xml
cp -u ~/Github/learnosm/_site/sitemap.xml ~/Github/LearnOSM-language-helper/sitemap/sitemap-1.xml
cd ~/Github/LearnOSM-language-helper/sitemap
#
### Edit sitemap-1.xml - remove the old header & insert a new one.
sed -i '1,2d' sitemap-1.xml
sed -i '1 r sitemap-header.xml' sitemap-1.xml
sed -i '1d' sitemap-1.xml
sed -i '/\<lastmod/d' sitemap-1.xml
sed -i 's/localhost\:4000/learnosm\.org/g' sitemap-1.xml
# sed -i 's/nl_NL/nl/g' sitemap-1.xml
# sed -i 's/zh_CN/zh/g' sitemap-1.xml
# sed -i 's/zh_TW/tw/g' sitemap-1.xml
sed -i '/org\/cs\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/de\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/en\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/es\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/fa\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/fr\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/hr\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/hu\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/id\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/it\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/ja\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/ko\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/my\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/nb\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/pl\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/pt\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/ru\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/sq\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/sw\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/uk\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/vi\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/</ r sitemap-1-lang.xml' sitemap-1.xml
sed -i '/org\/cs\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/de\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/en\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/es\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/fa\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/fr\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/hr\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/hu\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/id\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/it\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/ja\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/ko\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/my\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/nb\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/pl\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/pt\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/ru\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/sq\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/sw\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/uk\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/vi\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/contribute\/</ r sitemap-contribute.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/fa\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/hr\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/hu\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/ko\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/nb\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/ru\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/sq\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/uk\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/beginner\/</ r sitemap-b.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/fa\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/hr\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/hu\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/ko\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/nb\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/ru\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/sq\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/uk\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/beginner\/introduction\/</ r sitemap-b-intro.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/fa\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/hr\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/hu\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/ko\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/nb\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/ru\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/sq\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/uk\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/beginner\/start-osm\/</ r sitemap-b-start.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/ko\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/beginner\/id-editor\/</ r sitemap-b-id.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/beginner\/glossary\/</ r sitemap-b-gloss.xml' sitemap-1.xml
sed -i '/org\/cs\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/de\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/en\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/es\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/fa\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/fr\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/hr\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/id\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/it\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/ja\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/my\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/nb\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/pl\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/pt\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/ru\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/sw\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/uk\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/vi\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/beginner\/moving-forward\/</ r sitemap-b-mv-f.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/es\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/fr\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/nb\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/pl\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/pt\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/ru\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/sw\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/uk\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/josm\/</ r sitemap-j.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/es\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/fr\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/hr\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/pt\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/ru\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/sw\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/uk\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/josm\/start-josm\/</ r sitemap-j-start.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/hr\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/ru\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/sw\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/uk\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/zh_CN\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/josm\/more-about-josm\/</ r sitemap-j-more-abt.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/es\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/fr\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/hr\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/pt\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/ru\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/sw\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/uk\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/josm\/editing-with-josm\/</ r sitemap-j-edit-w.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/es\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/sw\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/josm-tools\/</ r sitemap-j-tools.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/es\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/fr\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/sw\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/josm-plugins\/</ r sitemap-j-plugins.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/es\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/josm-more-plugins\/</ r sitemap-j-m-plugins.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/josm\/josm-presets\/</ r sitemap-j-presets.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/creating-presets\/</ r sitemap-j-create-presets.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/creating-presets\/</ r sitemap-j-create-presets.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/creating-presets\/</ r sitemap-j-create-presets.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/creating-presets\/</ r sitemap-j-create-presets.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/creating-presets\/</ r sitemap-j-create-presets.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/creating-presets\/</ r sitemap-j-create-presets.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/creating-presets\/</ r sitemap-j-create-presets.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/creating-presets\/</ r sitemap-j-create-presets.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/creating-presets\/</ r sitemap-j-create-presets.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/josm-relations\/</ r sitemap-j-relations.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/josm-editing-techniques\/</ r sitemap-j-edit-tech.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/josm-editing-techniques\/</ r sitemap-j-edit-tech.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/josm-editing-techniques\/</ r sitemap-j-edit-tech.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/es\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/fr\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/pt\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/ci\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/josm\/aerial-imagery\/</ r sitemap-j-aerial.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/josm-adding-imagery\/</ r sitemap-j-add-imagery.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/josm-adding-imagery\/</ r sitemap-j-add-imagery.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/josm-adding-imagery\/</ r sitemap-j-add-imagery.xml' sitemap-1.xml
sed -i '/org\/fa\/josm\/josm-adding-imagery\/</ r sitemap-j-add-imagery.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/josm-adding-imagery\/</ r sitemap-j-add-imagery.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/josm-adding-imagery\/</ r sitemap-j-add-imagery.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/josm-adding-imagery\/</ r sitemap-j-add-imagery.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/josm-adding-imagery\/</ r sitemap-j-add-imagery.xml' sitemap-1.xml
sed -i '/org\/cs\/josm\/correcting-imagery-offset\/</ r sitemap-j-corr-offset.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/correcting-imagery-offset\/</ r sitemap-j-corr-offset.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/correcting-imagery-offset\/</ r sitemap-j-corr-offset.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/correcting-imagery-offset\/</ r sitemap-j-corr-offset.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/correcting-imagery-offset\/</ r sitemap-j-corr-offset.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/correcting-imagery-offset\/</ r sitemap-j-corr-offset.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/correcting-imagery-offset\/</ r sitemap-j-corr-offset.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/correcting-imagery-offset\/</ r sitemap-j-corr-offset.xml' sitemap-1.xml
sed -i '/org\/de\/josm\/josm-conflict-resolution\/</ r sitemap-j-conflict.xml' sitemap-1.xml
sed -i '/org\/en\/josm\/josm-conflict-resolution\/</ r sitemap-j-conflict.xml' sitemap-1.xml
sed -i '/org\/id\/josm\/josm-conflict-resolution\/</ r sitemap-j-conflict.xml' sitemap-1.xml
sed -i '/org\/it\/josm\/josm-conflict-resolution\/</ r sitemap-j-conflict.xml' sitemap-1.xml
sed -i '/org\/ja\/josm\/josm-conflict-resolution\/</ r sitemap-j-conflict.xml' sitemap-1.xml
sed -i '/org\/my\/josm\/josm-conflict-resolution\/</ r sitemap-j-conflict.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/josm\/josm-conflict-resolution\/</ r sitemap-j-conflict.xml' sitemap-1.xml
sed -i '/org\/vi\/josm\/josm-conflict-resolution\/</ r sitemap-j-conflict.xml' sitemap-1.xml
sed -i '/org\/cs\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/de\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/en\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/es\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/fa\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/it\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/ja\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/my\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/pl\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/sq\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/vi\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/hot-tips\/</ r sitemap-h-tips.xml' sitemap-1.xml
sed -i '/org\/de\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/en\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/fa\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/fr\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/it\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/ja\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/my\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/nl_NL\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/pl\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/vi\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
sed -i '/org\/zh_TW\/hot-tips\/getting-started\/</ r sitemap-h-start.xml' sitemap-1.xml
cp sitemap-1.xml ../output/sitemap.xml